version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_homologacao
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: homologacao
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: api_homologacao
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/homologacao
    ports:
      - '8000:8000'
    depends_on:
      - db

  web:
    build: ./web
    container_name: web_homologacao
    restart: unless-stopped
    ports:
      - '5173:5173'
    environment:
      VITE_API_URL: http://localhost:8000
    depends_on:
      - api

volumes:
  postgres_data:
